import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body
        className={`pt-12 w-full min-h-screen bg-lightorange ${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased`}
        style={{ fontFamily: 'Montserrat, Arial, sans-serif' }}
      >
         <Navbar />
        {children}
      </body>
    </html>
  );
}
